language: python
python: 3.6
before_script:
  - psql -c 'CREATE DATABASE travisci;' -U postgres
  - psql -c 'CREATE SCHEMA other;' -d travisci -U postgres
addons:
  postgresql: "9.4"
script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test
